version: '3.9'

services:
  app:
    image: 'order-management-app:latest'
    build:
      context: .
    ports:
      - "8080"
    deploy:
      mode: replicated
      replicas: 1
    networks:
      - order-management-app-network
  db:
    image: mysql
    restart: always
    container_name: order-management-db
    environment:
      MYSQL_ROOT_PASSWORD:
      MYSQL_DATABASE: order-management
      MYSQL_USER: root
      MYSQL_PASSWORD:
    ports:
      - '3306:3306'
    networks:
      - order-management-app-network
  prometheus:
    image: prom/prometheus:v2.35.0
    container_name: prometheus
    restart: unless-stopped
    ports:
      - "9090:9090"
    volumes:
      - ./data/prometheus/config:/etc/prometheus/
    command:
      - '--config.file=/etc/prometheus/prometheus.yaml'
    networks:
      - order-management-app-network
  grafana:
    image: grafana/grafana-oss:8.5.2
    pull_policy: always
    container_name: grafana
    restart: unless-stopped
    ports:
      - "3000:3000"
    volumes:
      - ./data/grafana:/var/lib/grafana
    environment:
      - GF_SECURITY_ADMIN_PASSWORD=admin
      - GF_SERVER_DOMAIN=localhost
    networks:
      - order-management-app-network
networks:
  order-management-app-network: