version: "3.7"
services:
  app:
    build: .
    restart: always
    ports:
      - 8080:8080
    networks:
      - order-management-net
    environment:
      - spring.datasource.url=jdbc:mysql://mysqldb:3306/order-management?createDatabaseIfNotExist=true&autoReconnect=true
      - spring.datasource.username=user
      - spring.datasource.password=123456
      - spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver
      - spring.jpa.hibernate.ddl-auto=update
      - spring.jpa.show-sql=true
    depends_on:
      - mysqldb
    volumes:
      - .m2:/root/.m2
  mysqldb:
    container_name: mysqldb
    image: "mysql:8.0"
    restart: always
    ports:
      - 3306:3306
    networks:
      - order-management-net
    environment:
      MYSQL_DATABASE: order-management
      MYSQL_USER: user
      MYSQL_PASSWORD: 123456
      MYSQL_ROOT_PASSWORD: 123456
  prometheus:
    image: prom/prometheus:v2.35.0
    container_name: prometheus
    restart: unless-stopped
    ports:
      - "9090:9090"
    volumes:
      - ./data/prometheus/config:/etc/prometheus/
    command:
      - '--config.file=/etc/prometheus/prometheus.yaml'
    networks:
      - order-management-net
  grafana:
    image: grafana/grafana-oss:8.5.2
    pull_policy: always
    container_name: grafana
    restart: unless-stopped
    ports:
      - "3000:3000"
    volumes:
      - ./data/grafana:/var/lib/grafana
    environment:
      - GF_SECURITY_ADMIN_PASSWORD=admin
      - GF_SERVER_DOMAIN=localhost
    networks:
      - order-management-net
networks:
  order-management-net:
